### PR TITLE
Added regression modeling for customer purchase predictions

### PR DESCRIPTION
**Pull request by MikeVitvi**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I updated the code to implement regression modeling for predicting customer purchase behavior. This involved integrating algorithms such as linear regression and decision tree regression to analyze how customer demographics, transaction history, and promotional discounts impact purchase amounts.
## What did you learn from the changes you have made?
From implementing regression modeling, I gained insights into:

Data Preparation: The importance of cleaning data and ensuring its suitability for modeling.
Variable Relationships: Understanding how customer attributes and transactional variables correlate with purchase amounts.
Model Evaluation: Using metrics like RMSE and R-squared to assess model performance and accuracy in predicting purchase behavior.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
An alternative approach considered was exploring more complex models such as ensemble methods (e.g., random forests, gradient boosting) to potentially improve prediction accuracy. Additionally, incorporating advanced feature engineering techniques like interaction terms or polynomial features could further enhance model performance.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
One challenge was ensuring the dataset was appropriately formatted and cleaned for regression analysis. Handling missing data and ensuring variables were correctly encoded required meticulous preprocessing steps. Techniques such as imputation for missing values and normalization were employed to address these challenges effectively.

## Checklist
- [ X ] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by Shiraz-Latif — CHANGES_REQUESTED** [review]
Thanks Mike for this contribution. Great work overall. 
Can you incorporate following changes. 
- no need to add anything that is already done in previous steps. 
- Remove Exploration of dataset because it was done earlier 
- remove # Import necessary libraries and other commands in this cell 
- you can keep # Explore variables: Gender and Location, # Plot Age vs Purchase Amount and # Explore location-based insights because those are new 
- add some results from your exploratory data analysis, just like we did in previous steps. 
- for regression, can you please print the result of the regression assessment so that we can either validate or reject the hypothesis. similar was done earlier for other variables so you can get help from that. 

-

**Review by Shiraz-Latif — APPROVED** [review]
This looks good now. Thanks

**Review by JessilynnKim — APPROVED** [review]
Thank you!

**Review by OlenaBolokhonova — APPROVED** [review]
Approved,good job,thank you for the contribution to the project

**Pull request merged**
