### PR TITLE
Libraries import, data import and performed basic EDA

### PR DESCRIPTION
**Pull request by Shiraz-Latif**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Imported required python libraries 
Imported the dataset that was selected 
performed basic EDA - to be continued 

## What did you learn from the changes you have made?
performing basic EDA in Python 

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
I was thinking to read csv directly from kaggle but then changed my mind to read from data folder. 

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
It took me some time to apply groupby on multiple aggregations. 

## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by OlenaBolokhonova — APPROVED** [review]
Approved pull-request

**Review by MikeVitvi — COMMENTED** [review]
Approved

**Review by MikeVitvi — COMMENTED** [review]
Approved

**Comment by JessilynnKim** [comment]
Approved

**Review by JessilynnKim — COMMENTED** [review]
Approved

**Pull request merged**
